// Code generated by MockGen. DO NOT EDIT.
// Source: gpunodepool_controller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sim "github.com/ishanchopra/gpu-scheduler/internal/sim"
)

// MockFleetRegistrar is a mock of FleetRegistrar interface.
type MockFleetRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockFleetRegistrarMockRecorder
}

// MockFleetRegistrarMockRecorder is the mock recorder for MockFleetRegistrar.
type MockFleetRegistrarMockRecorder struct {
	mock *MockFleetRegistrar
}

// NewMockFleetRegistrar creates a new mock instance.
func NewMockFleetRegistrar(ctrl *gomock.Controller) *MockFleetRegistrar {
	mock := &MockFleetRegistrar{ctrl: ctrl}
	mock.recorder = &MockFleetRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFleetRegistrar) EXPECT() *MockFleetRegistrarMockRecorder {
	return m.recorder
}

// DeleteFleet mocks base method.
func (m *MockFleetRegistrar) DeleteFleet(poolKey string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteFleet", poolKey)
}

// DeleteFleet indicates an expected call of DeleteFleet.
func (mr *MockFleetRegistrarMockRecorder) DeleteFleet(poolKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFleet", reflect.TypeOf((*MockFleetRegistrar)(nil).DeleteFleet), poolKey)
}

// FleetUsageForPool mocks base method.
func (m *MockFleetRegistrar) FleetUsageForPool(poolKey string) (sim.FleetUsage, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FleetUsageForPool", poolKey)
	ret0, _ := ret[0].(sim.FleetUsage)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// FleetUsageForPool indicates an expected call of FleetUsageForPool.
func (mr *MockFleetRegistrarMockRecorder) FleetUsageForPool(poolKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FleetUsageForPool", reflect.TypeOf((*MockFleetRegistrar)(nil).FleetUsageForPool), poolKey)
}

// RegisterFleet mocks base method.
func (m *MockFleetRegistrar) RegisterFleet(poolKey string, spec sim.GPUNodePoolSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterFleet", poolKey, spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterFleet indicates an expected call of RegisterFleet.
func (mr *MockFleetRegistrarMockRecorder) RegisterFleet(poolKey, spec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterFleet", reflect.TypeOf((*MockFleetRegistrar)(nil).RegisterFleet), poolKey, spec)
}
