// Code generated by MockGen. DO NOT EDIT.
// Source: simclient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sim "github.com/ishanchopra/gpu-scheduler/internal/sim"
)

// MockSimulatorClient is a mock of SimulatorClient interface.
type MockSimulatorClient struct {
	ctrl     *gomock.Controller
	recorder *MockSimulatorClientMockRecorder
}

// MockSimulatorClientMockRecorder is the mock recorder for MockSimulatorClient.
type MockSimulatorClientMockRecorder struct {
	mock *MockSimulatorClient
}

// NewMockSimulatorClient creates a new mock instance.
func NewMockSimulatorClient(ctrl *gomock.Controller) *MockSimulatorClient {
	mock := &MockSimulatorClient{ctrl: ctrl}
	mock.recorder = &MockSimulatorClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSimulatorClient) EXPECT() *MockSimulatorClientMockRecorder {
	return m.recorder
}

// Allocate mocks base method.
func (m *MockSimulatorClient) Allocate(workloadID string, gpuCount, memMiB int, profile string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allocate", workloadID, gpuCount, memMiB, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Allocate indicates an expected call of Allocate.
func (mr *MockSimulatorClientMockRecorder) Allocate(workloadID, gpuCount, memMiB, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allocate", reflect.TypeOf((*MockSimulatorClient)(nil).Allocate), workloadID, gpuCount, memMiB, profile)
}

// GetRunStatus mocks base method.
func (m *MockSimulatorClient) GetRunStatus(runID string) (sim.RunStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunStatus", runID)
	ret0, _ := ret[0].(sim.RunStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunStatus indicates an expected call of GetRunStatus.
func (mr *MockSimulatorClientMockRecorder) GetRunStatus(runID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunStatus", reflect.TypeOf((*MockSimulatorClient)(nil).GetRunStatus), runID)
}

// Start mocks base method.
func (m *MockSimulatorClient) Start(input sim.RuntimeInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockSimulatorClientMockRecorder) Start(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSimulatorClient)(nil).Start), input)
}

// Release mocks base method.
func (m *MockSimulatorClient) Release(workloadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", workloadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockSimulatorClientMockRecorder) Release(workloadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockSimulatorClient)(nil).Release), workloadID)
}
