// Code generated by MockGen. DO NOT EDIT.
// Source: gpuworkload_controller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sim "github.com/ishanchopra/gpu-scheduler/internal/sim"
)

// MockWorkloadRuntimeSimulator is a mock of WorkloadRuntimeSimulator interface.
type MockWorkloadRuntimeSimulator struct {
	ctrl     *gomock.Controller
	recorder *MockWorkloadRuntimeSimulatorMockRecorder
}

// MockWorkloadRuntimeSimulatorMockRecorder is the mock recorder for MockWorkloadRuntimeSimulator.
type MockWorkloadRuntimeSimulatorMockRecorder struct {
	mock *MockWorkloadRuntimeSimulator
}

// NewMockWorkloadRuntimeSimulator creates a new mock instance.
func NewMockWorkloadRuntimeSimulator(ctrl *gomock.Controller) *MockWorkloadRuntimeSimulator {
	mock := &MockWorkloadRuntimeSimulator{ctrl: ctrl}
	mock.recorder = &MockWorkloadRuntimeSimulatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkloadRuntimeSimulator) EXPECT() *MockWorkloadRuntimeSimulatorMockRecorder {
	return m.recorder
}

// Allocate mocks base method.
func (m *MockWorkloadRuntimeSimulator) Allocate(workloadID string, gpuCount, memMiB int) (*sim.Allocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allocate", workloadID, gpuCount, memMiB)
	ret0, _ := ret[0].(*sim.Allocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allocate indicates an expected call of Allocate.
func (mr *MockWorkloadRuntimeSimulatorMockRecorder) Allocate(workloadID, gpuCount, memMiB interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allocate", reflect.TypeOf((*MockWorkloadRuntimeSimulator)(nil).Allocate), workloadID, gpuCount, memMiB)
}

// AllocateWithOptions mocks base method.
func (m *MockWorkloadRuntimeSimulator) AllocateWithOptions(workloadID string, gpuCount, memMiB int, opts sim.AllocationOptions) (*sim.Allocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocateWithOptions", workloadID, gpuCount, memMiB, opts)
	ret0, _ := ret[0].(*sim.Allocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllocateWithOptions indicates an expected call of AllocateWithOptions.
func (mr *MockWorkloadRuntimeSimulatorMockRecorder) AllocateWithOptions(workloadID, gpuCount, memMiB, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocateWithOptions", reflect.TypeOf((*MockWorkloadRuntimeSimulator)(nil).AllocateWithOptions), workloadID, gpuCount, memMiB, opts)
}

// GetLatestRunStatusForWorkload mocks base method.
func (m *MockWorkloadRuntimeSimulator) GetLatestRunStatusForWorkload(workloadID string) (sim.RunStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRunStatusForWorkload", workloadID)
	ret0, _ := ret[0].(sim.RunStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestRunStatusForWorkload indicates an expected call of GetLatestRunStatusForWorkload.
func (mr *MockWorkloadRuntimeSimulatorMockRecorder) GetLatestRunStatusForWorkload(workloadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRunStatusForWorkload", reflect.TypeOf((*MockWorkloadRuntimeSimulator)(nil).GetLatestRunStatusForWorkload), workloadID)
}

// Preempt mocks base method.
func (m *MockWorkloadRuntimeSimulator) Preempt(workloadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preempt", workloadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Preempt indicates an expected call of Preempt.
func (mr *MockWorkloadRuntimeSimulatorMockRecorder) Preempt(workloadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preempt", reflect.TypeOf((*MockWorkloadRuntimeSimulator)(nil).Preempt), workloadID)
}

// Release mocks base method.
func (m *MockWorkloadRuntimeSimulator) Release(workloadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", workloadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockWorkloadRuntimeSimulatorMockRecorder) Release(workloadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockWorkloadRuntimeSimulator)(nil).Release), workloadID)
}

// StartWithRuntimeInput mocks base method.
func (m *MockWorkloadRuntimeSimulator) StartWithRuntimeInput(input sim.RuntimeInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartWithRuntimeInput", input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartWithRuntimeInput indicates an expected call of StartWithRuntimeInput.
func (mr *MockWorkloadRuntimeSimulatorMockRecorder) StartWithRuntimeInput(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartWithRuntimeInput", reflect.TypeOf((*MockWorkloadRuntimeSimulator)(nil).StartWithRuntimeInput), input)
}
