apiVersion: scheduler.ishanchopra.dev/v1alpha1
kind: GPUNodePool
metadata:
  name: gpunodepool-sample
  namespace: default
  labels:
    app.kubernetes.io/name: gpu-scheduler
    app.kubernetes.io/managed-by: kustomize
spec:
  nodeCount: 2
  devicesPerNode: 4
  memoryMiBPerDevice: 81920
  profile: h100_sxm
---
apiVersion: scheduler.ishanchopra.dev/v1alpha1
kind: GPUNodePool
metadata:
  name: gpunodepool-a100
  namespace: default
  labels:
    app.kubernetes.io/name: gpu-scheduler
    app.kubernetes.io/managed-by: kustomize
spec:
  nodeCount: 2
  devicesPerNode: 4
  memoryMiBPerDevice: 81920
  profile: a100_80gb
---
apiVersion: scheduler.ishanchopra.dev/v1alpha1
kind: GPUNodePool
metadata:
  name: gpunodepool-tpu-v5e
  namespace: default
  labels:
    app.kubernetes.io/name: gpu-scheduler
    app.kubernetes.io/managed-by: kustomize
spec:
  nodeCount: 2
  devicesPerNode: 4
  memoryMiBPerDevice: 16384
  profile: tpu_v5e_chip
