apiVersion: scheduler.ishanchopra.dev/v1alpha1
kind: GPUWorkload
metadata:
  labels:
    app.kubernetes.io/name: gpu-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: gpuworkload-sample
spec:
  # TODO(user): Add fields here
