//go:build !ignore_autogenerated

// Copyright (c) 2024 Ishan Chopra
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPreprocessRuntimeSpec) DeepCopyInto(out *DataPreprocessRuntimeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPreprocessRuntimeSpec.
func (in *DataPreprocessRuntimeSpec) DeepCopy() *DataPreprocessRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(DataPreprocessRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistillationRuntimeSpec) DeepCopyInto(out *DistillationRuntimeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistillationRuntimeSpec.
func (in *DistillationRuntimeSpec) DeepCopy() *DistillationRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(DistillationRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddingRuntimeSpec) DeepCopyInto(out *EmbeddingRuntimeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddingRuntimeSpec.
func (in *EmbeddingRuntimeSpec) DeepCopy() *EmbeddingRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(EmbeddingRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvalRuntimeSpec) DeepCopyInto(out *EvalRuntimeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvalRuntimeSpec.
func (in *EvalRuntimeSpec) DeepCopy() *EvalRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(EvalRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FineTuneRuntimeSpec) DeepCopyInto(out *FineTuneRuntimeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FineTuneRuntimeSpec.
func (in *FineTuneRuntimeSpec) DeepCopy() *FineTuneRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(FineTuneRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodePool) DeepCopyInto(out *GPUNodePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodePool.
func (in *GPUNodePool) DeepCopy() *GPUNodePool {
	if in == nil {
		return nil
	}
	out := new(GPUNodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNodePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodePoolList) DeepCopyInto(out *GPUNodePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUNodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodePoolList.
func (in *GPUNodePoolList) DeepCopy() *GPUNodePoolList {
	if in == nil {
		return nil
	}
	out := new(GPUNodePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNodePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodePoolSpec) DeepCopyInto(out *GPUNodePoolSpec) {
	*out = *in
	if in.DeviceType != nil {
		in, out := &in.DeviceType, &out.DeviceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodePoolSpec.
func (in *GPUNodePoolSpec) DeepCopy() *GPUNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(GPUNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodePoolStatus) DeepCopyInto(out *GPUNodePoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodePoolStatus.
func (in *GPUNodePoolStatus) DeepCopy() *GPUNodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(GPUNodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUWorkload) DeepCopyInto(out *GPUWorkload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUWorkload.
func (in *GPUWorkload) DeepCopy() *GPUWorkload {
	if in == nil {
		return nil
	}
	out := new(GPUWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUWorkloadList) DeepCopyInto(out *GPUWorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUWorkloadList.
func (in *GPUWorkloadList) DeepCopy() *GPUWorkloadList {
	if in == nil {
		return nil
	}
	out := new(GPUWorkloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUWorkloadSpec) DeepCopyInto(out *GPUWorkloadSpec) {
	*out = *in
	if in.MaxRuntimeSeconds != nil {
		in, out := &in.MaxRuntimeSeconds, &out.MaxRuntimeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Training != nil {
		in, out := &in.Training, &out.Training
		*out = new(TrainingRuntimeSpec)
		**out = **in
	}
	if in.Inference != nil {
		in, out := &in.Inference, &out.Inference
		*out = new(InferenceRuntimeSpec)
		**out = **in
	}
	if in.Eval != nil {
		in, out := &in.Eval, &out.Eval
		*out = new(EvalRuntimeSpec)
		**out = **in
	}
	if in.FineTune != nil {
		in, out := &in.FineTune, &out.FineTune
		*out = new(FineTuneRuntimeSpec)
		**out = **in
	}
	if in.RLHF != nil {
		in, out := &in.RLHF, &out.RLHF
		*out = new(RLHFRuntimeSpec)
		**out = **in
	}
	if in.Embedding != nil {
		in, out := &in.Embedding, &out.Embedding
		*out = new(EmbeddingRuntimeSpec)
		**out = **in
	}
	if in.DataPreprocess != nil {
		in, out := &in.DataPreprocess, &out.DataPreprocess
		*out = new(DataPreprocessRuntimeSpec)
		**out = **in
	}
	if in.Distillation != nil {
		in, out := &in.Distillation, &out.Distillation
		*out = new(DistillationRuntimeSpec)
		**out = **in
	}
	if in.Jitter != nil {
		in, out := &in.Jitter, &out.Jitter
		*out = new(JitterConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUWorkloadSpec.
func (in *GPUWorkloadSpec) DeepCopy() *GPUWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(GPUWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUWorkloadStatus) DeepCopyInto(out *GPUWorkloadStatus) {
	*out = *in
	if in.QueuedAt != nil {
		in, out := &in.QueuedAt, &out.QueuedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUWorkloadStatus.
func (in *GPUWorkloadStatus) DeepCopy() *GPUWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(GPUWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceRuntimeSpec) DeepCopyInto(out *InferenceRuntimeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceRuntimeSpec.
func (in *InferenceRuntimeSpec) DeepCopy() *InferenceRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JitterConfigSpec) DeepCopyInto(out *JitterConfigSpec) {
	*out = *in
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JitterConfigSpec.
func (in *JitterConfigSpec) DeepCopy() *JitterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(JitterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RLHFRuntimeSpec) DeepCopyInto(out *RLHFRuntimeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RLHFRuntimeSpec.
func (in *RLHFRuntimeSpec) DeepCopy() *RLHFRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(RLHFRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantQuota) DeepCopyInto(out *TenantQuota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantQuota.
func (in *TenantQuota) DeepCopy() *TenantQuota {
	if in == nil {
		return nil
	}
	out := new(TenantQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantQuota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantQuotaList) DeepCopyInto(out *TenantQuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TenantQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantQuotaList.
func (in *TenantQuotaList) DeepCopy() *TenantQuotaList {
	if in == nil {
		return nil
	}
	out := new(TenantQuotaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantQuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantQuotaSpec) DeepCopyInto(out *TenantQuotaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantQuotaSpec.
func (in *TenantQuotaSpec) DeepCopy() *TenantQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(TenantQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantQuotaStatus) DeepCopyInto(out *TenantQuotaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantQuotaStatus.
func (in *TenantQuotaStatus) DeepCopy() *TenantQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(TenantQuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingRuntimeSpec) DeepCopyInto(out *TrainingRuntimeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingRuntimeSpec.
func (in *TrainingRuntimeSpec) DeepCopy() *TrainingRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(TrainingRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}
