apiVersion: v1
kind: Service
metadata:
  name: kafka-kafka-exporter
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka-kafka-exporter
    strimzi.io/name: kafka-kafka-exporter
spec:
  type: ClusterIP
  selector:
    strimzi.io/name: kafka-kafka-exporter
  ports:
    - name: metrics
      port: 9404
      targetPort: 9404

